### ISSUE TITLE
make models/Session.js

### ISSUE THREAD

**Issue by karlnh** [bkorbsquare/Project-2#21]
This file will contain the structure for logging each new session started. It will contain:
- (primary key) id, auto-increments
- (foreign key) user id
- timestamp, for when the new chat session starts
- 
when a user enters into our chat and creates a session, the data above is appended to a chat_session database.

**Comment by karlnh** [comment]
instead of single simple timestamp, do:

session_begin: (timestamp thing)
session_end: (timestamp thing)

**Comment by allstarcoding777** [comment]
done
